version: '3'
services:
  mysql:
    container_name: mysql_db
    image: 'mysql:8'
    ports:
      - '7000:3306'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=root'
#    volumes:
#      - 'database_mysql:/var/lib/mysql'

  redis:
    image: redis:7
    ports:
      - '6379:6379'
#    volumes:
#      - 'redis_data:/data'

#volumes:
#  redis_data:
#  database_mysql:
