version: '3'
services:
  mysql:
    container_name: mysql_db
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
    volumes:
      - 'database_mysql:/var/lib/mysql'

volumes:
  database_mysql: