env: "local"  #local, prod
app:
  address: "localhost:8080" # change to 0.0.0.0:8080 to prod environment
db:
  user: "user"
  pass: "password"
  host: "localhost:3306"   # change to mysql to prod environment
  name: "GameReview"